services:
  isaac-lab:
    container_name: isaac-lab
    image: nvcr.io/nvidia/isaac-lab:${ISAAC_LAB_VERSION}
    entrypoint: bash
    stdin_open: true 
    tty: true        
    network_mode: host
    user: "${UID}:${GID}"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - PRIVACY_CONSENT=${PRIVACY_CONSENT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      # Official NVIDIA Cache Mappings
      - ${CACHE_DIR}/cache/kit:/isaac-sim/kit/cache:rw
      - ${CACHE_DIR}/cache/ov:/root/.cache/ov:rw
      - ${CACHE_DIR}/cache/pip:/root/.cache/pip:rw
      - ${CACHE_DIR}/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ${CACHE_DIR}/cache/computecache:/root/.nv/ComputeCache:rw
      - ${CACHE_DIR}/logs:/root/.nvidia-omniverse/logs:rw
      - ${CACHE_DIR}/data:/root/.local/share/ov/data:rw
      - ${CACHE_DIR}/documents:/root/Documents:rw
      # Your code mount
      - ../:/workspace/isaaclab/source/standalone/mina_project:rw
    working_dir: /workspace/isaaclab/source/standalone/mina_project